[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
Thebes = "8b424ff8-82f5-59a4-86a6-de3761897198"
